### ISSUE TITLE
CURSO SNIPER DE QUESTÕES 

### ISSUE THREAD

**Issue by mariaedbalieiro** [neelygenet/raposas#4]
O curso sniper de questões está dando erro para assistir, não carrega e quando tenta fazer o download do vídeo aparece erro 403.  Como proceder ? ESPECIFICAMENTE O MÓDULO 3 DE COMO ESTUDAR CADA MATÉRIA, 
 NENHUM VIDEO FUNCIONA

**Comment by neelygenet** [comment]
Problema resolvido.
